---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grayscale-nginx
  name: grayscale-nginx-0916
spec:
  replicas: 2
  selector:
    matchLabels:
      app: grayscale-nginx
  template:
    metadata:
      labels:
        app: grayscale-nginx
    spec:
      containers:
        - image: nexus.cmss.com:8086/cnp/nginx:1.20.7
          name: grayscale-nginx-0916
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: grayscale-nginx
  name: grayscale-nginx-0916
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 18080
  selector:
    app: grayscale-nginx
  type: LoadBalancer
---
