apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: my-app-0916
  namespace: default
spec:
  components:
    - name: my-app-0916
      type: webservice
      properties:
        image: nexus.cmss.com:8086/cnp/nginx:1.20.7 # {"$imagepolicy": "test-env-0914:test-app-0914-2"}
